language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- hhvm
env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=latest WP_MULTISITE=1
- WP_VERSION=4.1 WP_MULTISITE=0
- WP_VERSION=4.1 WP_MULTISITE=1
matrix:
  exclude:
    - php: 7.0
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=4.1 WP_MULTISITE=1
    - php: hhvm
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: hhvm
      env: WP_VERSION=4.1 WP_MULTISITE=1
  allow_failures:
  - php: hhvm
  fast_finish: true
before_script:
  - phpenv config-rm xdebug.ini
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: cd tests; phpunit;
notifications:
  slack:
    rooms:
      secure: e2xmbwOoagh/rZIqUnx15HcTv5hZGxykvg8Tj0ENGi/bLcXgrEYxs2hpW+nzGggmSl22Eh+6wLRo62L0dEIIo1n+yknqDdAbVG7lmnX7Tc45JNgxWtSmAPzC3wAp0e9w1hy8HILPjYLxl0G7eXUvo3mKVRCCyD/Cyz5dDicE8tQ=
    on_success: change
    on_failure: always
    on_start: always
